[workspace]
name = "strict-mojo"
version = "0.1.0"
description = "A comprehensive Mojo project template with Python packaging standards"
authors = ["Your Name <your.email@example.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
# Core development workflow - delegates to tasks.sh for strict checking
build = "./tasks.sh build"
run = "./tasks.sh run"
test = "./tasks.sh test"
clean = "./tasks.sh clean"

# Additional convenience tasks
format = "pixi run mojo format --quiet ."
format-check = "pixi run mojo format --check ."
dev-shell = "pixi shell"

[dependencies]
# Mojo runtime - lightweight template keeps only essentials
modular = "25.4.*"

# Python for interoperability - latest stable version
python = "3.13.*"

# Essential development tools
pip = "*"

[pypi-dependencies]
# Lightweight template - users can add their own dependencies
# Uncomment examples below as needed:
# numpy = "*"              # For numerical computing
# pytest = "*"             # For Python-style testing

[environments]
default = { solve-group = "default" }

[activation.env]
# Zero-tolerance strict runtime configuration
MOJO_PYTHON_INTEROP_WARNINGS = "error"
MOJO_ENABLE_ASSERTIONS = "1" 
MOJO_ASSERT_ON_ERROR = "1"
MOJO_DISABLE_OPTIMIZATIONS = "0"
