[workspace]
authors = ["Your Name <your.email@example.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "your-project-name"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = "./tasks.sh build"
run = "./tasks.sh run"
test = "./tasks.sh test"
clean = "./tasks.sh clean"

[dependencies]
# Mojo compiler - using 25.4.* for stability while allowing patch updates
modular = "25.4.*"

# Python interpreter for interop - 3.13+ for maximum type safety
# Python 3.13 includes: TypeIs, ReadOnly, default TypeVars, better error messages
# Using specific version (not >=) for reproducible strict builds
python = "3.13.*"

# pip for installing Python packages
pip = "*"

[pypi-dependencies]
# Add your Python dependencies here
# These will be available for import in Mojo via Python.import_module()
# Example: numpy = "*"
# Example: pandas = ">=2.0"

[environments]
default = { solve-group = "default" }

[activation.env]
# Treat all Python interop warnings as errors (no silent failures)
MOJO_PYTHON_INTEROP_WARNINGS = "error"

# Enable runtime assertions for debug_assert() statements
MOJO_ENABLE_ASSERTIONS = "1"

# Additional strict runtime checks
MOJO_ASSERT_ON_ERROR = "1"

# Keep optimizations enabled to catch more potential issues
# (Some bugs only appear with optimizations on)
MOJO_DISABLE_OPTIMIZATIONS = "0"
