name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: latest
        cache: true
    
    - name: Install dependencies
      run: pixi install
    
    - name: Build entire project
      run: pixi run build
    
    - name: Run tests
      run: pixi run test
    
    - name: Run examples
      run: |
        pixi run run examples/basic_usage.mojo
        pixi run run benchmarks/core_performance.mojo
